export const massData = [
  {
    _id: "1",
    image: "/assets/images/user4.png",
    name: "Gray Bright",
    username: "graybright29",
    massage:
      "Mollit veniam laboris non proident. Nulla Lorem sint fugiat sint fugiat reprehenderit excepteur laboris aliquip. Adipisicing ut aliqua eu mollit quis nostrud Lorem id adipisicing eu irure adipisicing et. Aute dolore cillum nisi aute aliquip non dolore proident exercitation anim laboris elit ex adipisicing. Est consequat voluptate esse cupidatat incididunt ad nisi qui magna. Magna culpa id amet qui excepteur tempor adipisicing irure adipisicing minim.\r\n",
    time: "06:00",
    active: false,
    read: true,
    muted: true,
    subscribed: false,
    profileLink: "endastfand/user/graybright29",
    pinned: ["m1-3"],
    conversation: [
      {
        id: "m1-1",
        sender: "receiver",
        receiver: "user",
        type: "text",
        message: "I am doing great!",
        date: "2024-03-18T12:00:00Z",
        replied: true,
      },
      {
        id: "m1-2",
        sender: "user",
        receiver: "receiver",
        type: "video",
        message: "assets/videos/video.mp4",
        date: "2024-03-19T12:05:00Z",
        paid: false,
      },
      {
        id: "m1-3",
        sender: "user",
        receiver: "receiver",
        type: "image",
        message: "assets/images/gallery1.jpg",
        date: "2024-03-18T12:05:00Z",
        paid: false,
        replied: true,
      },
      {
        id: "m1-4",
        sender: "receiver",
        receiver: "user",
        type: "text",
        message: "That’s awesome!",
        date: "2024-03-18T12:05:00Z",
        paid: false,
      },
      {
        id: "m1-5",
        sender: "receiver",
        receiver: "user",
        type: "image-text",
        message: "assets/images/gallery1.jpg",
        text: "hi",
        paid: false,
        date: "2024-03-19T12:00:00Z",
      },
      {
        id: "m1-6",
        sender: "user",
        receiver: "receiver",
        type: "text",
        message: "I am doing great!",
        date: "2024-03-19T12:05:00Z",
        paid: false,
      },
      {
        id: "m1-7",
        sender: "user",
        receiver: "receiver",
        message: "assets/videos/video.mp4",
        type: "video-text",
        text: "hi",
        date: "2024-03-19T12:05:00Z",
        paid: true,
      },
    ],
  },
  {
    _id: "2",
    image: "/assets/images/user4.png",
    name: "Gray Price",
    username: "grayprice29",
    massage:
      "Mollit veniam laboris non proident. Nulla Lorem sint fugiat sint fugiat reprehenderit excepteur laboris aliquip. Adipisicing ut aliqua eu mollit quis nostrud Lorem id adipisicing eu irure adipisicing et. Aute dolore cillum nisi aute aliquip non dolore proident exercitation anim laboris elit ex adipisicing. Est consequat voluptate esse cupidatat incididunt ad nisi qui magna. Magna culpa id amet qui excepteur tempor adipisicing irure adipisicing minim.\r\n",
    time: "06:00",
    profileLink: "endastfand/user/grayprice29",
    active: true,
    read: false,
    subscribed: true,
    muted: true,
    pinned: ["m2-1"],
    conversation: [
      {
        id: "m1-1",
        sender: "receiver",
        receiver: "user",
        type: "text",
        message: "I am doing great!",
        date: "2024-03-18T12:00:00Z",
        replied: true,
        paid: false,
      },
      {
        id: "m1-2",
        sender: "user",
        receiver: "receiver",
        type: "text",
        message: "That’s awesome!",
        date: "2024-03-18T12:05:00Z",
        paid: false,
      },
      {
        id: "m1-3",
        sender: "user",
        receiver: "receiver",
        type: "image",
        message: "assets/images/gallery1.jpg",
        date: "2024-03-18T12:05:00Z",
        paid: false,
      },
    ],
  },
];
